package logic;
/**
 * UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA
 * FACULTAD DE INGENIERIA
 * ESCUELA DE SISTEMAS Y COMPUTACION
 * SISTEMAS OPERATIVOS
 * SOFTWARE SIMULACION DE PROCESOS
 * @author CARLOS JAVIER PITA AMAYA
 * @author JHON JAIRO ZIPA CARO
 */

/**
 * 
 * ESTA CLASE PERMMITE CREAR PROCESOS CON SUS ATRIBUTOS
 *
 */
/**
 * CLLASE ENUMERADA 
 *
 */
public enum State {
	LISTO, FINALIZADO, BLOQUEADO, EN_EJECUCION
}
